server:
  port: 8800

spring:
  datasource:
    username: root
    password: als274213
    url: jdbc:mysql://121.4.40.144:3306/score?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # mapper-locations: ["classpath:/mapper/**/*.xml"]   # 配置.xml文件位置
  type-aliases-package: com.als.score.entity    # 配置别名，即在xml文件中可以不写全类名（可以不写包名）

logging:
  level:
    com.als.score: debug
    web: debug